### ISSUE TITLE
mosh binary returns network exception in LX branded zone

### ISSUE THREAD

**Issue by jevidl** [joyent/illumos-joyent#102]
I have run into an issue running the mobile shell binary in an LX branded zone. it returns the following error: 

Network exception: setsockopt: Invalid argument

I am opening here based on the issue I found in the mosh issue tracker, which suggests this is an issue with the emulation provided by LX branded zones. https://github.com/mobile-shell/mosh/issues/335

From the issue: 

> "After some thought, I think this is an emulation failure on the part of SmartOS. If it claims to be Linux 3.19, it should provide the functionality that glibc expects from a real Linux 3.19 kernel. I suggest reporting this as an issue against SmartOS or Illumos, whoever is the upstream that's responsible for the Linux emulation. Use strace or truss with mosh-server new and include that in the report."

As suggested, I have included the output of `strace -o mosh-trace.txt mosh-server new -v `

Here is the output of uname -a within my lx-branded zone: 
`Linux yankee 3.13.0 BrandZ virtual linux x86_64 x86_64 x86_64 GNU/Linux
`

I am happy to provide more info if needed, thanks. 

[mosh-trace.txt](https://github.com/joyent/illumos-joyent/files/196272/mosh-trace.txt)

**Comment by bcantrill** [comment]
I have a fix for this that I'll be pushing shortly -- and in testing this, I'm definitely becoming a mosh convert. ;)

**Comment by sjorge** [comment]
@bcantrill first htop, now mosh! Just stay away from systemd ;)

**Comment by bcantrill** [comment]
This was filed (and fixed) as [https://smartos.org/bugview/OS-5300](OS-5300) -- with our apologies for the inconvenience!
