### ISSUE TITLE
salt-minion wants /proc/self/mounts on LX

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#105]
Looks like saltstack wants /proc/self/mounts when using states related to mounts, this node does not seem to exists under lx branded zones.

Which looks to be the same as /proc/mounts at first glance.

**Comment by jjelinek** [comment]
This is open as OS-4026.

**Comment by sjorge** [comment]
Ah I didn't find that one, the internal bug tracker is not very search friendly.

**Comment by bcantrill** [comment]
As it turns out, SIGAR also ran into this and this issue has since been fixed as [OS-5481](https://smartos.org/bugview/OS-5481); closing this out.

**Comment by sjorge** [comment]
This is still failing for me in salt-minion, I will dig into that code once I am back from holiday.

(Seems to do with uid/gid not being mapped from name to id or visa versa)
