### ISSUE TITLE
setsockop fails with SOL_SOCK, SO_RECVUCRED [Chrome core dumps]

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#11]
'Google Chrome' fails when running inside an lx branded zone. (Using official 64-bit dataset)

setsockopt(10, SOL_SOCKET, SO_RECVUCRED, 0xFFFFFD7FFFDFE9E4, 4, SOV_DEFAULT) Err#22 EINVAL

Full truss available here: https://gist.github.com/sjorge/6ba0abc719f36c6f33fa
Core available here: http://sjorge.sinners.be/joyent/core.chrome.tar.bz2

**Comment by pfmooney** [comment]
This specific issue should be fixed in joyent/illumos-joyent@42ce707864693a4173f27ec86ed55c9df456855a.
That said, Chrome still is nonfunctional due to lack of user namespace support.

**Comment by sjorge** [comment]
I'll try chrome again in the next platform release. Hopefully indeed one browser will work now. (poke me if I forget)
