### ISSUE TITLE
zsh REPORTTIME regression in LX

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#116]
```
[artemis :: sjorge][~]
[.]$ /native/sbin/uname -a
SunOS artemis 5.11 joyent_20160527T033529Z i86pc i386 i86pc
/native/sbin/uname -a  7.41s user 8.98s system 169360% cpu 0.010 total
```

This was fixed a while ago but is now back!

**Comment by sjorge** [comment]
Meh seems it was never closed, I was convinced it was fixed... eh might have not touch a linux zone in a while then :p

**Comment by pfmooney** [comment]
@sjorge It's open as [OS-5374](https://smartos.org/bugview/OS-5374).
I have it thoroughly diagnosed, but stalled a little while implementing the fix.  It involves some changes to the native `wait(2)`/`waitid(2)` handling which requires gentle care.
