### ISSUE TITLE
iptun interfaces return class-based "natural" netmask when queried by ioctl(SIOCGLIFNETMASK)

### ISSUE THREAD

**Issue by joshado** [joyent/illumos-joyent#119]
I'm trying to run a Quagga instance on top of an IPsec tunnel and hitting an issue when quagga queries the interfaces' netmasks.
Specifically, the `SIOCGLIFNETMASK` ioctl used by quagga appears to be returning the class-based netmask, rather than what I would expect (a `/30` for an IPv4 P2P link), causing all manner of havoc for quagga's routing protocols, since they see an invalid locally connected route.

---

To set the scene, I'm creating a simple / representative version of my environment with the following commands (obviously the remote iptun address is invalid, but it doesn't matter for the purposes of this issue):

```
dladm create-iptun -T ipv4 -a local=<local host ip>,remote=10.99.99.99 tun3
ipadm create-addr -T static -a local=172.16.0.1,remote=172.16.0.2 tun3/v4
```

This brings up the tunnel and configures a P2P ip address. I've written a super-simple script to call the ioctl in question:

```
// compile with gcc -lnsl -lsocket ioctl_test.c
#include <unistd.h>
#include <stropts.h>
#include <inet/ip.h>
#include <sys/sockio.h>
#include <strings.h>
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
  struct lifreq lifr;
  int s = socket(AF_INET, SOCK_DGRAM, 0);
  strncpy(lifr.lifr_name, argv[1], sizeof(lifr.lifr_name));
  if(ioctl(s, SIOCGLIFNETMASK, (caddr_t)&lifr) < 0) {
    perror("ioctl(SIOCGLIFNETMASK)");
    exit(1);
  }
  printf("Netmask is: %i\n", lifr.lifr_addrlen);
  return 0;
}
```

Running this on the tunnel I just created yields the output:

```
[root@router_c ~]# ./a.out tun3
Netmask is: 16
```

Tellingly, if I change the tunnel addresses to a different class, I get:
```
[root@router_c ~]# ipadm delete-addr tun3/v4
[root@router_c ~]# ipadm create-addr -Tstatic -a local=10.0.0.1,remote=10.0.0.2 tun3/v4
[root@router_c ~]# ./a.out tun3
Netmask is: 8
```

So it would seem the netmask is being defaulted to a class-based netmask, which is wholly inappropriate for this kind of interface and totally screwing with Quagga :)

I'm still trying to work out _how_ this netmask is being set on the interface, just about to go dtracing the `ipif_set_default` method, which is called during the `ipadm create-addr` calls, and itself calls out to `ip_net_mask` to set the "natural" netmask for an IP address.

https://github.com/joyent/illumos-joyent/blob/master/usr/src/uts/common/inet/ip/ip_if.c#L14214-L14224

---
I'm also posting as I investigate further to give someone the chance to tell me my assumptions are wrong and that this is the intended behaviour of IP tunnels.

Cheers!

**Comment by rmustacc** [comment]
Thanks for reporting this. One thing I notice is that by default create-addr's synopsis indicates that you should specify a prefix. Is there a reason you didn't specify either one of those? Not sure if that's what's going on or related, but I suspect it might be part of what's causing this to happen.

**Comment by joshado** [comment]
Bother, thats probably what it is. I'll have another go later on when I'm in front of my laptop and close the issue if it is a PEBCAK error.

Thanks for having a look.

**Comment by rmustacc** [comment]
Sounds good. Let us know if we can improve some of the docs here to make
this less likely to happen if that's what it turns out to be.

**Comment by joshado** [comment]
Yeah, I read that argument in the doc as either "local=foo,remote=bar" or "a.b.c.d/xy", not both combined. For some reason I presumed the p2p link wouldn't need a prefix.

**Comment by joshado** [comment]
Bother, I realise now where I went wrong early on:

```
[root@router_a ~]# ipadm create-addr -Tstatic -a local=10.0.0.1/30,remote=10.0.0.2/30 tun1/v4
ipadm: Error in setting remote address: Invalid address
```

So I've been foolishly assuming a P2P link with a netmask was invalid. I should have been concentrating more, as, lo:

```
[root@router_a ~]# ipadm create-addr -Tstatic -a local=10.0.0.1/30,remote=10.0.0.2 tun1/v4
[root@router_a ~]# ./a.out tun1
Netmask is: 30
```

What a fool. Thanks for setting me straight @rmustacc. 

I'm wondering if the documentation could be broken out to make this less ambiguous:

```
     ipadm create-addr [-t] -T static [-d]
           -a [local|remote=]addr[/prefixlen]... addrobj
```
changed to become
```
     ipadm create-addr [-t] -T static [-d]
           -a addr[/prefixlen] addrobj
     ipadm create-addr [-t] -T static [-d]
           -a local=addr[/prefixlen],remote=addr addrobj
```

Let me know what you think and I have a look at a PR.
Cheers :)

**Comment by rmustacc** [comment]
On 6/5/16 14:43 , Thomas Haggett wrote:
> Bother, I realise now where I went wrong early on:
> 
> ```
> [root@router_a ~]# ipadm create-addr -Tstatic -a local=10.0.0.1/30,remote=10.0.0.2/30 tun1/v4
> ipadm: Error in setting remote address: Invalid address
> ```
> 
> So I've been foolishly assuming a P2P link with a netmask was invalid. I should have been concentrating more, as, lo:
> 
> ```
> [root@router_a ~]# ipadm create-addr -Tstatic -a local=10.0.0.1/30,remote=10.0.0.2 tun1/v4
> [root@router_a ~]# ./a.out tun1
> Netmask is: 30
> ```

ipadm could probably be a bit more helpful there. It seems pretty
natural to set the prefix on both from a user perspective. We should
probably error if they're different, but not if they're the same. I
would definitely blame ipadm for this.

> I'm wondering if the documentation could be broken out to make this less ambiguous:
> 
> ```
>      ipadm create-addr [-t] -T static [-d]
>            -a [local|remote=]addr[/prefixlen]... addrobj
> ```
> changed to become
> ```
>      ipadm create-addr [-t] -T static [-d]
>            -a addr[/prefixlen] addrobj
>      ipadm create-addr [-t] -T static [-d]
>            -a local=addr[/prefixlen],remote=addr addrobj
> ```

We could probably do that in the interim, but I'm more tempted
personally to just fix the program to make sure that if the prefix is
the same for both local and remote it works.

What do you think about that?

@danmcd, @jclulow thoughts on that?

**Comment by danmcd** [comment]
If you're using iptun as a LAN-like interface (which is possible if the other side reaches all of the other nodes) you should have local/remote match prefixes.

Some might question the virtue of using iptun as a LAN-like interface (as opposed to being strictly a point-to-point one), but since we can plumb it as a LAN-like interface, we should put the safety belts on per @rmustacc .
