### ISSUE TITLE
dladm create-iptun segfault

### ISSUE THREAD

**Issue by tuxillo** [joyent/illumos-joyent#123]
Hi,

While messing around with dladm:

```
# dladm create-iptun -T ipv4 -a local=172.16.12.10,remote tun0
Segmentation Fault (core dumped)
```

It's probably invalid syntax for the dladm command but it shouldn't segfault. Trace is:

> $C
> 08047318 libc.so.1`strlen+0x30(804780d, 0, 401, fee2c574)
> 08047368 iptun_process_addrarg+0x8d(8047de7, 8047400, 80473a8, feea4d82)
> 080473a8 iptun_process_args+0x78(6, 8047cac, 80688d6, 8047400, 80473fc, 80473dc)
> 08047c28 do_create_iptun+0x33(6)
> 08047c68 main+0xb9(8047c5c, fef1a768, 8047c9c, 8056ac7, 7, 8047ca8)
> 08047c9c _start+0x83(7, 8047db0, 8047db6, 8047dc3, 8047dc6, 8047dcb)

Let me know if the core file is needed.

Best regards,
Antonio Huete

**Comment by domag02** [comment]
See here: [illumos issue #9121](https://www.illumos.org/issues/9121)

**Comment by tuxillo** [comment]
Already solved in illumos
