### ISSUE TITLE
"unsupported mixed cpu monitor/mwait support detected" on ThinkStation E30

### ISSUE THREAD

**Issue by danielkasza** [joyent/illumos-joyent#130]
One of my computers cannot boot the stock SmartOS platform images.
- Lenovo ThinkStation E30, Xeon E3-1235
- Panic message: `unsupported mixed cpu monitor/mwait support detected`

OmniOS, and OpenIndiana fail to boot with the same message. It appears that the boot CPU does not report `mwait` capability _(disabled by BIOS maybe?)_, but the other CPUs do.

The computer is stable with only one core enabled.

The computer is also stable with [this patch](https://gist.github.com/danielkasza/313a70ce310b62b6ea36c2cccc6ef60c) and all cores enabled.
Note that the new condition matches the comment that was originally there. The computer still prints warnings about the feature mismatch.

**Comment by pfmooney** [comment]
Open as [OS-5698](https://smartos.org/bugview/OS-5698)

Thanks

**Comment by danielkasza** [comment]
[`/proc/cpuinfo` from Linux](https://gist.github.com/danielkasza/a75b6aae8bf1362dd321ae236c8aa8e2)

Note that processor 0 does not have the `monitor` flag, but all other processors do.

**Comment by pfmooney** [comment]
This has been fixed since 277b243c5e83fcf2b763b300fcd3042a88dd2eac.
