### ISSUE TITLE
netatalk causes a CN to become unresponsive under certain conditions

### ISSUE THREAD

**Issue by themisanthrope** [joyent/illumos-joyent#137]
Reproducible on at least two platforms, the most recent being `20170119T014129Z`.

```
{
  "brand": "joyent",
  "limit_priv": "default",
  "v": 1,
  "create_timestamp": "2016-10-20T16:11:16.479Z",
  "image_uuid": "adf9565c-8be6-11e6-a077-57637270218d",
  "max_msg_ids": 4096,
  "max_sem_ids": 4096,
  "max_shm_ids": 4096,
  "max_shm_memory": 1536,
  "nics": [
    {
      "interface": "net0",
      "gateway": "10.0.48.129",
      "gateways": [
        "10.0.48.129"
      ],
      "netmask": "255.255.255.128",
      "ip": "10.0.48.133",
      "ips": [
        "10.0.48.133/25"
      ],
      "mtu": 1500,
      "primary": true
    }
  ],
  "resolvers": [
    "10.0.0.133",
    "10.0.0.134"
  ],
  "cpu_shares": 12,
  "max_lwps": 4000,
  "zfs_io_priority": 16000,
  "max_physical_memory": 1536,
  "max_locked_memory": 1536,
  "max_swap": 3072,
  "cpu_cap": 500,
  "zone_state": "running",
  "zoneid": 1,
  "last_modified": "2017-02-05T06:44:04.000Z",
  "firewall_enabled": false,
  "platform_buildstamp": "20170119T014129Z",
  "state": "running",
  "boot_timestamp": "2017-01-25T19:19:23.000Z",
  "pid": 5040,
  "tags": {
    "triton.cns.services": "unix,images-hot,afp-images",
    "os": 20113,
    "backup": true
  },
  "quota": 650,
  "zfs_root_compression": "lz4",
  "zfs_root_recsize": 131072,
  "zpool": "zones",
}
```
_Some information has been removed from this zone description_

Extra packages installed from `pkgsrc`: `ansible`, `gcc47`, `gmake`, `libevent`, `libgcrypt`, `openssl`, `syncthing`

Software installed from source: `http://downloads.sourceforge.net/project/netatalk/netatalk/3.1.10/netatalk-3.1.10.tar.gz`

Services enabled: `smb/server`, `smb/client`, `rpc/bind`, `idmap`, `netatalk`, `syncthing (custom manifest)`

Extra `pam` services: `pam_smb_passwd`

Zone purpose: Act as an AFP and SMB fileserver, hosting assets used by the Design and Marketing teams. The vast majority of users connect with AFP, with a handful of SMB connections for those unfortunate enough to use Windows.

--------------------------

Acting as a standalone fileserver, this zone functions as expected. Syncthing is used to replicate assets with another fileserver (of the same configuration) running on a different CN.

There are another six file servers (three pairs) with the same configuration, but hosting different files.

To improve performance, load is balanced between the pairs of hosts using `haproxy`, which runs on our routers (`FreeBSD 10.3-RELEASE-p9`). This also works fine, until we start using TCP availability checks.
The availability checks run against port 548, and only check that the port is open. If `netatalk` dies, the port gets closed and the fileserver is removed from the pool.

Each CN has four of these zones running, with an availability check running every 1000ms. After about 10 hours, the CNs became unresponsive;

- Unable to connect by SSH
- CN agent stopped responding, causing the host to be marked **UNAVAILABLE** by `Triton`
- `Zabbix` agent stopped responding, causing the host to be marked as **DOWN** by `Zabbix`
- Some other zones on these CNs stopped responding altogether
- Other zones on these CNs started to act unpredictably
- The CNs still responded to ping
- Logging in to the CNs was still possible via IPMI SOL and local console
- When logged in, some commands (like `vmadm *`) cause the console to hang and never return
- When logged in, some commands (like `zpool *`) function without issue and provide sane information

I could only find two ways to get the CNs out of this state: Issue `reboot` from the IPMI SOL or local console (which would cause the CN to switch back to **RUNNING** in `Triton` momentarily before the reboot, or to send an IPMI NMI.

I did try manually killing the zone processes, but this didn't help.

I can make the dumps produced by the NMI instruction available, from both CNs. There are several.

--------------------------

I've resolved this issue internally by using a different method for health checking and feeding the information to `haproxy`, and I suspect that root of the issue may actually be with `netatalk` (I'll be raising an issue with them, too).

I'm raising this issue here because a fault inside a zone or with a zone process shouldn't (in my mind) have the potential to take out a whole host machine, and I'm hoping that the information here (along with the dumps) might help with isolating a potential OS availability bug too.

**Comment by bahamat** [comment]
I'll e-mail you some links to upload to Manta.

**Comment by themisanthrope** [comment]
Thanks! I've started the upload, I'll email you once they're complete.

**Comment by bahamat** [comment]
I've received the files. For posterity, they're in thoth with the following IDs

* db2eadb3e2d2d1e942bbe963e59160b5
* a7940d328216ea4ff787bc61dd9e592e
* 0a4c56c54cfb497e87fe839daadf8641

I've filed [OS-5957](https://smartos.org/bugview/OS-5957) internally to track this.

**Comment by themisanthrope** [comment]
Wonderful - let me know if you need anything else!

**Comment by themisanthrope** [comment]
This appears to have been rectified in a platform update.
