### ISSUE TITLE
KVM crashing in latest build

### ISSUE THREAD

**Issue by GernotS** [joyent/illumos-joyent#154]
I have a reproducible crash in KVM since the last few commits.

panic[cpu6]/thread=ffffff19609e9b00:
BAD TRAP: type=e (#pf Page fault) rp=ffffff007d4ed3a0 addr=0 occurred in module "kvm" due to a NULL pointer dereference

qemu-system-x86_:
#pf Page fault
Bad kernel fault at addr=0x0
pid=4048, pc=0xfffffffff7d23563, sp=0xffffff007d4ed490, eflags=0x10282
cr0: 80050033<pg,wp,ne,et,mp,pe> cr4: 1426f8<smep,osxsav,vmxe,xmme,fxsr,pge,mce,pae,pse,de>
cr2: 0
cr3: 1032dcf000
cr8: 0

        rdi: fffffffffbc1c020 rsi: ffffff1962b75ea0 rdx: ffffff19609e9b00
        rcx:                4  r8: ffffff1962b74fb0  r9: ffffff1962b74fb4
        rax:                0 rbx: ffffff196e935000 rbp: ffffff007d4ed4c0
        r10:                1 r11:                0 r12: ffffff1962b77d80
        r13: ffffff196e935280 r14:              210 r15:       3400000001
        fsb: fffffd7fef0f2a40 gsb: ffffff194d123080  ds:                0
         es:                0  fs:                0  gs:                0
        trp:                e err:                0 rip: fffffffff7d23563
         cs:               30 rfl:            10282 rsp: ffffff007d4ed490
         ss:               38

ffffff007d4ed280 unix:real_mode_stop_cpu_stage2_end+b22c ()
ffffff007d4ed390 unix:trap+e08 ()
ffffff007d4ed3a0 unix:_cmntrap+e6 ()
ffffff007d4ed4c0 kvm:kvm_create_vm+280 ()
ffffff007d4ed4e0 kvm:kvm_dev_ioctl_create_vm+27 ()
ffffff007d4edcc0 kvm:kvm_ioctl+718 ()
ffffff007d4edd00 genunix:cdev_ioctl+39 ()
ffffff007d4edd50 specfs:spec_ioctl+60 ()
ffffff007d4edde0 genunix:fop_ioctl+55 ()
ffffff007d4edf00 genunix:ioctl+9b ()
ffffff007d4edf10 unix:brand_sys_syscall+21a ()

dump available

**Comment by GernotS** [comment]
until https://github.com/joyent/illumos-joyent/commit/1a4f10250275489e9b68c1c49f1898674317a616 all is good. Later builds seem to harm KVM.

**Comment by danmcd** [comment]
A quick peek of a disassembled kvm module indicates this section of code:

```
714  	kvmp->kvm_kstat->ks_data = &kvmp->kvm_stats;
715  	kvmp->kvm_kstat->ks_data_size +=
716  	    strlen(curproc->p_zone->zone_name) + 1;
717  
```

I'm guessing curproc->p_zone is NULL.  Next question is, how would that happen?

**Comment by pfmooney** [comment]
@GernotS Are you building illumos-joyent/SmartOS yourself?  If so, ensure that the KVM portion of the build (located in `smartos-live/projects/local/kvm`) is cleaned and rebuilt.  Changes to kernel structures such as `proc_t` can result in misbehavior if dependent components (which include KVM) if they aren't rebuilt as well.

**Comment by GernotS** [comment]
Yes, I´m building myself.
I guess a gmake clean should take care of the kvm part as well?
I´m pretty confident I did that, but will re-do to verify.

**Comment by GernotS** [comment]
after a full clean and re-build kvm seems to be working again.
Issue can be closed, sorry for the hassle.

thanks

**Comment by danmcd** [comment]
No problem, good there's a public record of what happens in situations like this.
