### ISSUE TITLE
readlink("/proc/self/exe") can fail in lx zone with lofs dataset

### ISSUE THREAD

**Issue by citrus-it** [joyent/illumos-joyent#161]
I've created an LX branded zone with an extra dataset coming directly from the zones pool via lofs and am having trouble starting JVM when it is a couple of directory levels down on that dataset.

This looks a lot like https://smartos.org/bugview/OS-5167 that was fixed by @pfmooney a couple of years ago.

I replicated this with a small C program:

```
#include <stdio.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>

int
main()
{
        char buf[0x400];
        ssize_t ret;

        ret = readlink("/proc/self/exe", buf, sizeof(buf));

        if (ret > 0)
                printf("BUF: %.*s\n", ret, buf);
        else
                printf("RET: %d - %s\n", ret, strerror(errno));

        return 0;
}
```

and delegated a dataset to an Alpine Linux LX zone:

```
[root@smartos ~]# vmadm get 3caaf33a-bdf0-4cf3-db85-f9c714abf19d
...
  "filesystems": [
    {
      "source": "/zones/test",
      "target": "/test",
      "type": "lofs"
    }
  ],
...
```

And tested as follows:

```
caaf33a-bdf0-4cf3-db85-f9c714abf19d:/test# find . -exec ls -ld {} +
drwxr-xr-x    5 root     root             5 Mar  2 17:24 .
drwxr-xr-x    4 root     root             4 Mar  2 17:24 ./1
drwxr-xr-x    2 root     root             3 Mar  2 17:23 ./1/2a
-rwxr-xr-x    1 root     root         10768 Mar  2 17:23 ./1/2a/test
drwxr-xr-x    2 root     root             3 Mar  2 17:23 ./1/2b
lrwxrwxrwx    1 root     root            10 Mar  2 17:23 ./1/2b/test -> ../2a/test
drwxr-xr-x    2 root     root             3 Mar  2 17:24 ./1a
-rwxr-xr-x    1 root     root         10768 Mar  2 17:24 ./1a/test
drwxr-xr-x    2 root     root             3 Mar  2 17:24 ./1b
lrwxrwxrwx    1 root     root            10 Mar  2 17:24 ./1b/test -> ../1a/test
```

When only one level deep, it works as expected:

```
3caaf33a-bdf0-4cf3-db85-f9c714abf19d:/test/1/2b# cd /test/1a
3caaf33a-bdf0-4cf3-db85-f9c714abf19d:/test/1a# ./test
BUF: /test/1a/test
3caaf33a-bdf0-4cf3-db85-f9c714abf19d:/test/1a# cd ../1b
3caaf33a-bdf0-4cf3-db85-f9c714abf19d:/test/1b# ./test
BUF: /test/1a/test
```

but go one level further...

```
3caaf33a-bdf0-4cf3-db85-f9c714abf19d:/test# cd /test/1/2a
3caaf33a-bdf0-4cf3-db85-f9c714abf19d:/test/1/2a# ./test
BUF: /test/1/2a/test
3caaf33a-bdf0-4cf3-db85-f9c714abf19d:/test/1/2a# cd ../2b
3caaf33a-bdf0-4cf3-db85-f9c714abf19d:/test/1/2b# ./test
RET: -1 - No such file or directory
```

strace/truss also shows `readlink("/proc/self/exe")` is returning `ENOENT`

**Comment by jclulow** [comment]
What platform version are you using?  (`uname -v` in the global zone, or a native zone; `/native/usr/bin/uname -v` in an LX zone)

**Comment by citrus-it** [comment]
I just updated before re-testing this - 
```
[root@smartos ~]# uname -v
joyent_20180203T031130Z
```

**Comment by citrus-it** [comment]
I've done some more work on this and here's what is going on.

`readlink(/proc/self/exe)` effectively just calls `vnodetopath()` on the `p->p_exec` vnode. This does not always has a cached v_path which is why the readlink does not always succeed. The lofs mount scenario that is described earlier in this ticket is just one way to trigger this.

Comparing with the native /proc code that handles `readlink(/proc/self/path/a.out)` - https://github.com/joyent/illumos-joyent/blob/master/usr/src/uts/common/fs/proc/prvnops.c#L6247 - I can see that the mechanism there is rather different.

In the native /proc code, `vnodetopath(p->p_exec)` is used only as a fallback mechanism. The primary method is to call `vnodetopath(p->p_execdir)` to get the path for the executable's parent directory, and then to find the `p->p_exec` vnode via a couple of methods. First checking if the file called `u_comm` is the correct vnode, and otherwise iterating the parent directory to find the correct vnode.

Rather than moving entirely to that approach, I've tested a solution which tries the `p->p_exec` vnode first and if that does not have a cached v_path, falls back to iterating the `p->p_execdir` directory to find it. In testing this resolved the problem - I'll open up a PR for this shortly.
