### ISSUE TITLE
pargs for bhyve shows unexting arguments

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#169]
When running pargs against a bhyve process it shows one unexiting argument:

```-B 1,manufacturer=Joyent,product=SmartDC HVM,version=7.20180420T221403Z,serial=f3e59c75-51a8-e862-b7e1-8e3265fd555c,sku=001,family=Virtual Machine```

This is a not a valid parameter for bhyve, you can see this if you pass the exact parameters to bhyve in the global zone.

@jlevon might be related to one of your recent commits where zhyve got re-exec to bhyve?

**Comment by mgerdts** [comment]
Did you put quotes around the stuff after -B?  That should be one argument
but has multiple spaces.

**Comment by sjorge** [comment]
I did but I only wrapped them around "manufacturer=Joyent,product=SmartDC HVM,version=7.20180420T221403Z,serial=f3e59c75-51a8-e862-b7e1-8e3265fd555c,sku=001,family=Virtual Machine", seems the 1 is also needed.
