### ISSUE TITLE
panic in mac_util with debug build

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#174]
```
panic[cpu7]/thread=fffffe00f8ef8c40: assertion failed: IPH_HDR_VERSION(ip6h) == IPV6_VERSION, file: ../../common/io/mac/mac_util.c, line: 539

fffffe00f8ef8130 genunix:process_type+16b0c0 ()
fffffe00f8ef81b0 mac:mac_ip_hdr_length_v6+6f ()
fffffe00f8ef8250 mac:mac_rx_srs_long_fanout+1e3 ()
fffffe00f8ef8b00 mac:mac_rx_srs_fanout+2a2 ()
fffffe00f8ef8b80 mac:mac_rx_srs_drain+2f2 ()
fffffe00f8ef8c20 mac:mac_rx_srs_poll_ring+2fa ()
fffffe00f8ef8c30 unix:thread_start+8 ()
```

This is illumos-joyent with 8da8197608a9f1e993f8ab217c01026d6619f4b8, I first noticed it when testing a patch to netstat from Andyf but it happens without it too.

vmdump available, just ask me on in #smartos

**Comment by sjorge** [comment]
Tagging @pfmooney the last few commits look like they are from you, well and Jerry but those got backed out again.

**Comment by sjorge** [comment]
```> $c
vpanic()
0xfffffffffbe13588()
mac_ip_hdr_length_v6+0x6f(fffffeb3270c1684, fffffeb3270c16b8, fffffe00f8ef81ec, fffffe00f8ef81ef, 0)
mac_rx_srs_long_fanout+0x1e3(fffffeb6fb6fb340, fffffeb37029d280, 86dd, 12, fffffe00f8ef8ab8, fffffe00f8ef8abc)
mac_rx_srs_fanout+0x2a2(fffffeb6fb6fb340, fffffeb45e81b980)
mac_rx_srs_drain+0x2f2(fffffeb6fb6fb340, 1000)
mac_rx_srs_poll_ring+0x2fa(fffffeb6fb6fb340)
thread_start+8()
> ::findstack -v
Usage: address::findstack [-v]
> fffffeb3270c1684::print -t ip6_t
ip6_t {
    union  ip6_ctlun = {
        struct ip6_hdrctl ip6_un1 = {
            uint32_t ip6_un1_flow = 0x34000045
            uint16_t ip6_un1_plen = 0
            uint8_t ip6_un1_nxt = 0x40
            uint8_t ip6_un1_hlim = 0
        }
        uint8_t ip6_un2_vfc = 0x45
    }
    struct in6_addr ip6_src = 4006:c5be:a17:a97:4275:1de3:ed21:1bb
    struct in6_addr ip6_dst = 232f:8ffb:7051:7008:8010:80a:f826:0
}```

Taking some first steps into mdb

**Comment by danmcd** [comment]
The outer header has the additional clue:

```
> fffffeb3270c1672::print -a "struct ether_vlan_header"
fffffeb3270c1672 {
    fffffeb3270c1672 ether_dhost = {
        fffffeb3270c1672 ether_addr_octet = [ 0xd2, 0x89, 0x66, 0xb4, 0xd1, 0xdb ]
    }
    fffffeb3270c1678 ether_shost = {
        fffffeb3270c1678 ether_addr_octet = [ 0x78, 0x4f, 0x43, 0x25, 0xb, 0x91 ]
    }
    fffffeb3270c167e ether_tpid = 0x81
    fffffeb3270c1680 ether_tci = 0xa00
    fffffeb3270c1682 ether_type = 0xdd86
}
```
That ether_type is 0x86dd (pre-host-byteswap), which is ETHERTYPE_IP6.  So a sender (your gateway?) is encapsulating an IPv4 packet in an IPv6 Ethernet frame.  We shouldn't panic, and were it not for the ASSERT() we'd likely have this packet make it up to IPv6, where it would drop the packet on a reality check here:

https://grok.elemental.org/source/xref/illumos-joyent/usr/src/uts/common/inet/ip/ip6_input.c?r=1a34bcea#302

**Comment by sjorge** [comment]
10.23.10.151 would be an iOS device, if you have and ip for the 2nd one I could probably tell what the source device was.

**Comment by danmcd** [comment]
The 66.... address belongs to Adobe Systems according to whois, but reverse-DNS is failing on it currently.

**Comment by sjorge** [comment]
Yep, so it looks like a connection from the iPhone -> something at adobe, it probably did not pass through the firewall yet because it would have been NATed if it did. So I think I’m this case the iPhone is the one doing the odd stuff.

**Comment by sjorge** [comment]
Booted on a PI with a patch Dan send me, I was able to trigger the dump twice today. But it might just have been luck. So far no crash after about 30 min of uptime.

**Comment by danmcd** [comment]
So it crashed even with the patch?!

**Comment by danmcd** [comment]
A good test would be to send ICMP{,v6} ECHO REQUEST messages that look good, but are in the wrong ethernet frame.

**Comment by sjorge** [comment]
Ah sorry no, I meant I was able to trigger it 2 times before, but not with the patch so far.
Not sure how to send a ICMP with the wrong ether frame, I was mucking around in lightroom a bit to see if that would trigger it. (As that is the only thing on my phone from adobe) still running so far.

**Comment by sjorge** [comment]
This for fixed a while ago, closing
