### ISSUE TITLE
illumos#10055 and OS-7672 disagree

### ISSUE THREAD

**Issue by rmustacc** [joyent/illumos-joyent#198]
I was looking at an issue in the ahciem logic and I noticed that the two approaches basically disagree and you've ended up in a situation where you VERIFY a mutex is owned that you exit right before calling it. OS-7672 assumes that the mutex is held, but illumos#10055 drops it. I'd suggest you match upstream.

**Comment by jlevon** [comment]
Thanks Robert, I put this in Jira as https://smartos.org/bugview/OS-8037
