### ISSUE TITLE
lx brand has native process with UID 16 running without a proper mapping

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#24]
This is a minor one but I always look at my processes while trying to track down a problem.
I found one with UID 16 which did not exist in /etc/passwd... It's a native process so probably started at zone init.

http://i.imgur.com/NcQVy0q.png

Injecting some common UID/GID's used that do not conflict at zone install would be nice.

**Comment by sjorge** [comment]
Closing this here, It's more at home for who ever spins the images. Not sure where to log that though.

**Comment by bahamat** [comment]
I think @chorrell can find a home for this.

**Comment by pfmooney** [comment]
There's been talk of (perhaps conditionally) hiding native processes from lx_proc.  It's likely we'll punt on this issue until more clarity is reached.

**Comment by sjorge** [comment]
And perhaps /native's ps can just map the uid/gid to the gz's passwd and group files?

**Comment by jjelinek** [comment]
The native ps running inside the zone does not have access to the GZ passwd and group files.
