### ISSUE TITLE
lx brand - regression of rsyslogd?

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#25]
Hey All,

rsyslog is hanging again on update! we had this a while ago too and it got fixed by @bcantrill.
This time it seems to be in the starting phase not the stopping one.

To replicate:
1. build a fresh smartos image
(2. do a fresh install - optional)
3. import either the 64-bit or 32-bit image
4. provision either one of the images
5. ```aptitude update```
6. ```aptitude upgrade```
7. watch it hang on rsyslog update

@nshalman confirmed he could replicate. *sad puppies all around*

Filing a bug since a regression like this may get overlooked in the spreadsheet, I got a truss output but it does not tell (me) much.

http://sjorge.sinners.be/illumos/joyent/rsyslogd_regession/

Happy hunting, feel free to reach out to me on IRC if you have any questions

**Comment by pfmooney** [comment]
Open as https://smartos.org/bugview/OS-3704.
I'll take a look tomorrow.
