### ISSUE TITLE
lx brand no /proc/net/{tcp,udp,tpc6,udp6}

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#26]
lx brand is missing some bits in /proc/net, e.g. ```ss``` wants to use those.

They provide info about open tcp and udp connections.

**Comment by lloydde** [comment]
Thanks @sjorge. Moved to jira, https://smartos.org/bugview/OS-3740 .

**Comment by lloydde** [comment]
This is believed resolved with 28c5a398965e748ca8d8e6e58ffb37958575cce7 .

**Comment by sjorge** [comment]
Correct, netstat is even working (partial now) !

**Comment by lloydde** [comment]
Cool @sjorge!
