### ISSUE TITLE
lx brand: stop wrapping /bin/netstat with native netstat

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#28]
linux netstat is working with latest network bits

https://gist.github.com/sjorge/e7f4151793801b0a6c95

**Comment by pfmooney** [comment]
Tracking my lx_proc work needed for this in: https://smartos.org/bugview/OS-3485
Once that's complete, I'll likely open another ticket to remove the netstat replacement in lx ubuntu.

Thanks
