### ISSUE TITLE
lx_boot_zone_redhat relies on /tmp being cleared on reboot

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#29]
The lx_boot_zone_redhat relies on /tmp being cleared on a reboot/halt.
This will remove ```/tmp/.lx_net_up``` allow the network to start again on the next zone boot.

However on CentOS /tmp does not get cleared on reboot/halt. (using a minimal install) -- also same behavior on a vm.

**Comment by sjorge** [comment]
I had a vague recollection of there being a cronjob to clean /tmp and /var/tmp from my RHEL 5 sysadmin days... seems I was correct: http://superuser.com/a/582176

**Comment by pfmooney** [comment]
Open as: https://smartos.org/bugview/OS-3808
