### ISSUE TITLE
lx - '/proc/vmstat' missing

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#33]

**Comment by pfmooney** [comment]
Were there specific programs attempting to access this data?

**Comment by sjorge** [comment]
Yes, I think I documented it in the spreadsheet

**Comment by sjorge** [comment]
some nagios memory/swap plugins and ajenti for example seem to want it.

**Comment by pfmooney** [comment]
Open as https://smartos.org/bugview/OS-3821
