### ISSUE TITLE
varpd, -fstack-protector woes

### ISSUE THREAD

**Issue by rmustacc** [joyent/illumos-joyent#339]
While testing out -fstack-protector on illumos-joyent both @danmcd and @arekinath found a core dump in varpd that had a stack that looked like the following:

```
> ::status
debugging core file of varpd (32-bit) from curly
initial argv: /usr/lib/varpd/varpd
threading model: raw lwps
status: process terminated by SIGABRT (Abort)
> $C
f8fd8e78 libc.so.1`syscall+0x13(feee8fa4, 1c, 3fabfe2b, 0, f8fd8ea8, feddc000)
f8fd8e98 0xfee6d56f(4)
f8fd8ea8 libvarpd.so.1`__stack_chk_fail_local+0x17(80b9010, 0, f8fd8f68, 811edf4, ffffffff, ffffffff)
f8fd8ef8 libvarpd.so.1`libvarpd_overlay_inject(80eaee8, 810d160, 811e804, 811edf4)
f8fd8f38 libvarpd.so.1`libvarpd_plugin_proxy_ndp+0x106(818ee78, 810d160, 810d160)
f8fd8f68 libvarpd_svp.so.1`varpd_svp_lookup+0x6b(818ee08, 810d160, 810d160, 810d1b0)
f8fd8f98 libvarpd.so.1`libvarpd_overlay_lookup_handle+0x73(80eaee8)
f8fd8fc8 libvarpd.so.1`libvarpd_overlay_lookup_run+0x43(80eaee8)
f8fd8fe8 libc.so.1`_thrp_setup+0x81(fc9bda40)
f8fd8ff8 libc.so.1`_lwp_start(fc9bda40, 0, 0, 0, 0, 0)
```

Looking at the implementation of `libvarpd_overlay_inject_common` the main thing on the stack is the `overlay_targ_pkt_t`. This structure is notable due to having a different size in 32-bit and 64-bit software due to including a pointer and thus isn't part of the libvarpd type checks. The kernel has an `overly_targ_pkt32_t`. If you look at the two types in CTF / mdb, you'll find they have the same offsets for the structure. However, there is a critical difference, the kernel version is four bytes larger than the 32-bit version due to the compiler padding it out. The following diff seemed to fix it for @arekinath:

```
diff --git a/usr/src/uts/common/sys/overlay_target.h b/usr/src/uts/common/sys/overlay_target.h
index ae92ef3532..db9f4b67a9 100644
--- a/usr/src/uts/common/sys/overlay_target.h
+++ b/usr/src/uts/common/sys/overlay_target.h
@@ -180,12 +180,14 @@ typedef struct overlay_targ_pkt {
 
 #ifdef _KERNEL
 
+#pragma pack(4)
 typedef struct overlay_targ_pkt32 {
        uint64_t        otp_linkid;
        uint64_t        otp_reqid;
        uint64_t        otp_size;
        caddr32_t       otp_buf;
 } overlay_targ_pkt32_t;
+#pragma pack()
 
 #endif /* _KERNEL */
```

**Comment by danmcd** [comment]
Now aka OS-8245, https://smartos.org/bugview/OS-8245

**Comment by rmustacc** [comment]
It looks like this was merged. Do you want to close this @danmcd?

**Comment by danmcd** [comment]
Ooops, overlooked this.  Closing now.
