### ISSUE TITLE
lx-brand: jemalloc  test cores (maybe related to OS-3711: lxbrand plex dying in jemalloc)

### ISSUE THREAD

**Issue by h0lzi** [joyent/illumos-joyent#34]
Took some time to dig into this too. Not sure if this is related but might be worth looking at:

joyent_20150219T102159Z

image_uuid": "14a960b0-614e-11e4-a095-eb789315ae39

configure --enable-debug

make check

test/unit/junk
test_junk_small: pass
test_junk_large: pass
<jemalloc>: src/chunk.c:132: Failed assertion: "p[i] == 0"
Aborted (core dumped)
Test harness error

stack
LMfd`libc.so.1`syscall+0x30()
LMfd`lx_brand.so.1`lx_emulate+0x17c(7fffffefef30)
LMfd`lx_brand.so.1`lx_handler+0xa0()
libc.so.6`gsignal+0x39()
jet_chunk_alloc+0x198()
jet_huge_palloc+0x8c()
jet_huge_malloc+0x2b()
jet_imalloct+0x83()
imallocx+0xd2()
jet_mallocx+0x2de()
test_junk+0x77()
test_junk_huge+0x61()
p_test+0xad()
main+0x2e()
libc.so.6`__libc_start_main+0xf5()

does not happen with non debug build. So could be an error in the debug code too.
On a "normal" ubuntu tests do pass though with --enable-debug.

**Comment by pfmooney** [comment]
Yeah, memory corruption was the furthest I got with my diagnosis in OS-3711.
There are some pending LX changes I want to test against, once they land.
I'll add your notes to the OS-3711 ticket on the presumption that they're related.

Thanks
