### ISSUE TITLE
latest builds hang on centos again

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#35]
@nshalman reported this on IRC. I could reproduce.
NMI triggered vmdump: http://sjorge.sinners.be/illumos/joyent/centos_hang.vmdump.bz2

Ran yum update twice, 2nd time it hung.

**Comment by rmustacc** [comment]
Does the physical machine hang in this case? Or was it the centos processes themselves that were hanging?

**Comment by sjorge** [comment]
The entire zone. Even vmadm stop -f timed out

**Comment by rmustacc** [comment]
Okay, so the host as a whole is working, but you can't access the zone when this occurs, ping the zone's IP, etc. that right? And in this state other zones are working fine?

**Comment by sjorge** [comment]
The zone was completely unresponsive. GZ was fine, no other zones were running at the time.

**Comment by nshalman** [comment]
When it happened to me the whole machine became unresponsive. It was a physical machine that I couldn't NMI. It was reproducible with both my own build and the official build from today.

**Comment by bcantrill** [comment]
This is an in-kernel deadlock and a recent regression; I filed OS-4004, so I'm closing this out here. (Expect a fix for this today.)
