### ISSUE TITLE
iproute2's ip wants: SIOCGIFXQLEN

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#37]
iproute2 seems to also want SIOCGIFXQLEN.
Not sure if there was an internal bug for this yet, I think @pfmooney mentiond there was.

But I could not find it.

**Comment by bahamat** [comment]
This is [OS-3791][1].

[1]: https://smartos.org/bugview/OS-3791

**Comment by sjorge** [comment]
Closing here, seems there is indeed already one.
