### ISSUE TITLE
LX Partial support for NO_NEW_PRIVS and SECCOMP (for Elasticsearch 8)

### ISSUE THREAD

**Issue by smokris** [joyent/illumos-joyent#383]
Elasticsearch 8.0, [currently in beta](https://github.com/elastic/elasticsearch/releases?q=8.0.0), fails to run in a SmartOS LX zone with this error:

> unable to install syscall filter: java.lang.UnsupportedOperationException: seccomp unavailable: requires kernel 3.5+ with CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER compiled in at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:331)

In prior Elasticsearch versions you could disable that requirement by setting `bootstrap.system_call_filter: false`, but [that flag has been removed in Elasticsearch 8.0](https://www.elastic.co/guide/en/elastic-stack/8.0/elasticsearch-breaking-changes.html#system-call-filter-setting).

In order to [pass Elasticsearch's SystemCallFilter checks](https://github.com/elastic/elasticsearch/blob/v8.0.0-beta1/server/src/main/java/org/elasticsearch/bootstrap/SystemCallFilter.java), LX needs to:

|Requirement | Status as of PI 20211216T012707Z
|- | -
|return 0 for `prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0)` [indicating](https://man7.org/linux/man-pages/man2/prctl.2.html) process privileges have been successfully restricted | ⚠️ LX [already returns 0](https://github.com/joyent/illumos-joyent/blob/eb9ef5d332a9360d61d14bc65f06b393da776cc8/usr/src/uts/common/brand/lx/syscall/lx_prctl.c#L288), but it doesn't actually change process privileges or keep track of the NO_NEW_PRIVS status
|return 1 for `prctl(PR_GET_NO_NEW_PRIVS, 0, 0, 0, 0)` indicating NO_NEW_PRIVS is set | ⚠️ LX currently sets `errno=EINVAL`
|set `errno=EFAULT` for `prctl(PR_SET_SECCOMP, SECCOMP_MODE_FILTER, 0, 0, 0)` indicating the BPF pointer passed in arg3 is invalid (NULL) | ⚠️ LX currently sets `errno=EINVAL`
|return 0 for `prctl(PR_SET_SECCOMP, SECCOMP_MODE_FILTER, pointer, 0, 0)` indicating the filter has been successfully installed | ⚠️ LX currently sets `errno=EINVAL`
|return 2 for `prctl(PR_GET_SECCOMP, 0, 0, 0, 0)` indicating that SECCOMP_MODE_FILTER is enabled | ⚠️ LX currently sets `errno=EINVAL`

**Comment by danmcd** [comment]
How have you tested this?

**Comment by danmcd** [comment]
I understand you're new.  We can provide a bit of help for builds, including getting you up and building SmartOS on your own.  (NOTE: It's winter break time so latency & jitter will be high.)

**Comment by bahamat** [comment]
The related PR has been merged. Closing.
