### ISSUE TITLE
lx-brand Segmenation fault in vala Programm (quine-relay)

### ISSUE THREAD

**Issue by h0lzi** [joyent/illumos-joyent#44]
Created a Dockerimage for https://github.com/mame/quine-relay (Not sure if it works on "normal" Linux docker host, can't test at the Moment. But would guess it does.) It cores.
###########################
###########################

valac QR.vala
In file included from /usr/local/share/quine-relay/QR.vala.c:6:
In file included from /usr/include/glib-2.0/glib-object.h:23:
In file included from /usr/include/glib-2.0/gobject/gbinding.h:29:
In file included from /usr/include/glib-2.0/gobject/gobject.h:29:
In file included from /usr/include/glib-2.0/gobject/gboxed.h:27:
/usr/include/glib-2.0/gobject/glib-types.h:346: warning: multi-character character constant
./QR > QR.v
Segmentation fault (core dumped)

core and binary here: http://buildfarm.opencsw.org/~jh/quine.tar.gz

coal platform: joyent_20150320T005835Z

Testing: docker run -t holzi/quine-relay

(of cause it should run all the way to be a cool demo :) )

As this is based on Ubuntu 14.10 don't know how good that works with lx-brand anyway.

**Comment by bcantrill** [comment]
Very peculiar.  This binary is odd in that it has no PT_PHDR -- which results in it being exec()'d with a NULL brk. However, fixing this (that is, allowing it to get the proper brk despite the missing PT_PHDR) still results in a core dump. I have verified that the binary works on stock 14.04, so despite its peculiarities, it should be made to work on LX. Will investigate further tomorrow...

**Comment by h0lzi** [comment]
It's a quine so it's for sure peculiar. Updated my docker image to try 14.04 got a core too. Trying 12.04 now. But will probably be the same.

**Comment by bcantrill** [comment]
I still don't know how you managed to generate a binary that is missing a PT_PHDR, but it doesn't particularly matter -- we should be able to execute such binaries, and we can't (or rather couldn't). This has been addressed via https://smartos.org/bugview/OS-4128, which was fixed as https://github.com/joyent/illumos-joyent/commit/eb43e635cc8bd644a9afc675b8d6b35329b486aa.

**Comment by h0lzi** [comment]
ok more inside to it for reference:
tcc somehow triggers this:

oot@88ae9619d6b1:/usr/local/share/quine-relay# CC=tcc valac QR.vala
In file included from /usr/local/share/quine-relay/QR.vala.c:6:
In file included from /usr/include/glib-2.0/glib-object.h:23:
In file included from /usr/include/glib-2.0/gobject/gbinding.h:29:
In file included from /usr/include/glib-2.0/gobject/gobject.h:29:
In file included from /usr/include/glib-2.0/gobject/gboxed.h:27:
/usr/include/glib-2.0/gobject/glib-types.h:346: warning: multi-character character constant
root@88ae9619d6b1:/usr/local/share/quine-relay# 

root@88ae9619d6b1:/usr/local/share/quine-relay# /native/usr/bin/elfdump QR |more 
ELF Header
  ei_magic:   { 0x7f, E, L, F }
  ei_class:   ELFCLASS64          ei_data:       ELFDATA2LSB
  ei_osabi:   ELFOSABI_NONE       ei_abiversion: 0
  e_machine:  EM_AMD64            e_version:     EV_CURRENT
  e_type:     ET_EXEC
  e_flags:                     0
  e_entry:             0x80482e0  e_ehsize:     64  e_shstrndx:  27
  e_shoff:                0xbe20  e_shentsize:  64  e_shnum:     28
  e_phoff:                  0x40  e_phentsize:  56  e_phnum:     4

Program Header[0]:
    p_vaddr:      0x8048120           p_flags:    [ PF_R ]
    p_paddr:      0x8048120           p_type:     [ PT_INTERP ]
    p_filesz:     0x1c                p_memsz:    0x1c
    p_offset:     0x120               p_align:    0x1


root@88ae9619d6b1:/usr/local/share/quine-relay# valac QR.vala
root@88ae9619d6b1:/usr/local/share/quine-relay# /native/usr/bin/elfdump QR |more 
ELF Header
  ei_magic:   { 0x7f, E, L, F }
  ei_class:   ELFCLASS64          ei_data:       ELFDATA2LSB
  ei_osabi:   ELFOSABI_NONE       ei_abiversion: 0
  e_machine:  EM_AMD64            e_version:     EV_CURRENT
QR: ELFOSABI_NONE object has Linux .note.ABI-tag section. Assuming ELFOSABI_LINUX
  e_type:     ET_EXEC
  e_flags:                     0
  e_entry:              0x4005b0  e_ehsize:     64  e_shstrndx:  27
  e_shoff:                0xda00  e_shentsize:  64  e_shnum:     30
  e_phoff:                  0x40  e_phentsize:  56  e_phnum:     9

Program Header[0]:
    p_vaddr:      0x400040            p_flags:    [ PF_X PF_R ]
    p_paddr:      0x400040            p_type:     [ PT_PHDR ]
    p_filesz:     0x1f8               p_memsz:    0x1f8
    p_offset:     0x40                p_align:    0x8


the CC=tcc is needed by the quine-relay to work
