### ISSUE TITLE
lx-brand lisaac cores

### ISSUE THREAD

**Issue by h0lzi** [joyent/illumos-joyent#46]
reproduce:
joyent_20150330T233217Z

lx-ubuntu 14.04

apt-get install lisaac

run lisaac

\# lisaac
Bus error (core dumped)

core and qr.li at http://buildfarm.opencsw.org/~jh/lisaac.tar.bz2

qr.li source code from quine-relay which should be compiled with lisaac:

\# lisaac qr.li

resuliting programm should of cause run too :)

**Comment by bcantrill** [comment]
You ran out of memory:

```
$ elfdump -n core.lisaac.20338
...
        pr_info:
            si_signo:   [ SIGBUS ]
            si_errno:   [ ENOMEM ]
            si_code:    [ BUS_OBJERR ]
            si_addr:    0x00007fffc214d000
...
```

(In LX, mappings of anonymous memory are MAP_NORESERVE.)  I recommend at least 4G to run the quine relay.  This failure mode definitely needs to be more clear, but that's a separate issue. ;)
