### ISSUE TITLE
unicorn doesn't work with lx zones

### ISSUE THREAD

**Issue by bbhoss** [joyent/illumos-joyent#48]
I'm trying to use the unicorn application server, which uses kgio under the covers. There are some odd issues with unix socket mode that I need to look into later, but the TCP socket mode (`listen 3000`) doesn't work at all.

When the workers come up i get this error: https://gist.github.com/bbhoss/05ef9ed5f0e725800701

Output of `dtrace -n 'lx-syscall::accept*:return/execname == "ruby"/{ @[probefunc, arg1] = count(); }'`

    accept4                                                         -22            32670 

A snippet of `dtrace -n 'lx-syscall::accept4:entry/execname == "ruby"/{ printf("%d, %d, %d, %d", arg0, arg1, arg2, arg3) }`

     45  15048                    accept4:entry 9, 140737487300080, 140737487300076, 524288
     45  15048                    accept4:entry 9, 140737487300288, 140737487300284, 524288
     45  15048                    accept4:entry 9, 140737487300288, 140737487300284, 524288
     45  15048                    accept4:entry 9, 140737487300288, 140737487300284, 524288
     45  15048                    accept4:entry 9, 140737487300288, 140737487300284, 524288

I also ran the tests of kgio, and I got these failures. I'm unsure if they're related: https://gist.github.com/bbhoss/849b92199fc0bae5958a

Finally, I am seeing some odd issues with Puma as well, but haven't been able to investigate them yet. They may be related to this. When sending PUTs/POSTs, I get this: https://gist.github.com/bbhoss/cb260e0208c3707f962c

**Comment by bixu** [comment]
@bbhoss, would you be willing to contribute a test encapsulating your findings to the lx_kitchen project?  https://github.com/bixu/lx_kitchen/issues/5

**Comment by bbhoss** [comment]
If it's as simple as it looks, sure

**Comment by bixu** [comment]
It's pretty straightforward.  Test Kitchen supports Bats, shUnit2, RSpec, Serverspec, so take your pick.

**Comment by bbhoss** [comment]
Any update on this? It's all that's left before I can test my entire existing stack using LX zones. Also, it seems like this project is much less active. If needed, I can open something up on the smartos-live one.

**Comment by lloydde** [comment]
@bbhoss where you able to get help @bixu get an automated test together?

**Comment by pfmooney** [comment]
@bbhoss I'm looking into today.
I was able to reproduce with a sample rails app under unicorn.

**Comment by bbhoss** [comment]
Awesome. @lloydde I wasn't able to figure out how to use BATS properly with daemons, but I contributed what I could to demonstrate. It's a pretty simple issue really, it seems @pfmooney was able to get it reproduced already.

Thanks folks!

**Comment by pfmooney** [comment]
Open as: https://smartos.org/bugview/OS-4200

**Comment by bbhoss** [comment]
Thanks. I would check out the referenced pull if you want to simplify things. You don't need a full rails app, just a simple rackup hello world file.

**Comment by lloydde** [comment]
@bbhoss my rubyfoo is weak, link to a rackup hello world example?

**Comment by bbhoss** [comment]
```bash
apt-get install unicorn #On Ubuntu 14.04 they have it in apt
curl https://gist.githubusercontent.com/bbhoss/501436de9a8bd2f835b7/raw/6689933ad3c1aaddb5b2368685a8c36d9c1ffdbc/gistfile1.rb > /tmp/example.ru
}
unicorn /tmp/example.ru
```

**Comment by lloydde** [comment]
@bbhoss could you test this again? We believe this is resolved and my testing hasn't found any new issues.

**Comment by bbhoss** [comment]
It works! Thanks a ton guys, great work!

**Comment by daanemanz** [comment]
We have confirmed cases with Unicorn in LX zones running on more recent versions (after `20170916T185242Z`, which still works) of SmartOS. In particular, `20180412T010206Z` seems to be affected.
