### ISSUE TITLE
lx-brand: fuse emulation?

### ISSUE THREAD

**Issue by sjorge** [joyent/illumos-joyent#53]
Probably going to be too much work, but a lot of things use fuse on linux.
Lot of crypto stuff, opening exotic containers,... would be nice to have.

But it's not super important.

**Comment by pfmooney** [comment]
Given the lack of FUSE support in native illumos, this is probably a long way off.

**Comment by sjorge** [comment]
I'll close it for now then, as it's more a feature than an issue.
