### ISSUE TITLE
[lx] Assertion failed: ucp != NULL

### ISSUE THREAD

**Issue by rzezeski** [joyent/illumos-joyent#61]
`Assertion failed: ucp != NULL, file ../common/lx_brand.c, line 793`

I found a test which trips this assert often. The
`conformance/interfaces/pthread_join/6-3` test of the [Open POSIX
TestSuite][ts] which involves threads and signals.

[ts]: http://posixtest.sourceforge.net/

I ran this test via the [Autotest][] framework but it might take less
time to directly use posixtest. Here are the steps for running via
autotest:

[Autotest]: http://autotest.github.io/

```
# yum -y install git gcc tar patch gdb
# git clone --recursive git://github.com/autotest/autotest.git
# cd autotest
# ./client/autotest-local run posixtest

...wait a while, lots of tests run and may take an hour...

# cd client/tmp/posixtest/src
# ./t0 240 conformance/interfaces/pthread_join/6-3.test
```

**Comment by rzezeski** [comment]
This test also trips the assert:

`./t0 240 conformance/interfaces/pthread_create/14-1.test`

**Comment by jjelinek** [comment]
Opened OS-4470 to track this internally

**Comment by jaredmorrow** [comment]
Just for reference, this can also easily be triggered by installing any Haskell dependency via `cabal`
