### ISSUE TITLE
[lx] clock_getres(2) always returns 0 when ts is NULL

### ISSUE THREAD

**Issue by rzezeski** [joyent/illumos-joyent#66]
The lx clock_getres(2) emulation is slightly wrong. When `tp == NULL`
it always returns success without actually checking the clock id,
whereas Linux checks the validity of the clock.

From what I can tell the only reliance on this behavior is glibc's
(2.19) clock_getcpuclockid(3). I.e. it relies on this behavior to
verify the generated clock id before returning it to the user.

http://code.metager.de/source/xref/gnu/glibc/sysdeps/unix/sysv/linux/clock_getcpuclockid.c#33

(Note that the link is latest code but 2.19 is the same.)

I'm not sure if this really effects many programs. I found this bug
via the posix test suite:

`conformance/interfaces/clock_getcpuclockid/1-2`

**Comment by jjelinek** [comment]
I opened bug OS-4601 to track this.
