### ISSUE TITLE
[lx] sched_rr_get_internval() doesn't update timespec

### ISSUE THREAD

**Issue by rzezeski** [joyent/illumos-joyent#67]
The [current][rr] lx emualtion of `sched_rr_get_interval()` does not
update the passed-in timespec as it should. Discovered via the PTS
test `conformance/interfaces/sched_rr_get_interval/2-1`.

I have a patch incoming.

[rr]: https://github.com/joyent/illumos-joyent/blob/master/usr/src/lib/brand/lx/lx_brand/common/sched.c#L459

**Comment by pfmooney** [comment]
Open as [OS-4615](https://smartos.org/bugview/OS-4615)
