### ISSUE TITLE
lx socket TCP_KEEPIDLE can only be 10seconds+

### ISSUE THREAD

**Issue by h0lzi** [joyent/illumos-joyent#73]
You can only set TCP_KEEPIDLE to be 10 seconds+

small test programm from here:
https://github.com/joyent/node/issues/21080

set to e.g. 5 seconds:

LX_DEBUG:
41224/1:        setsockopt(9, 6, 4, 0x7fffffefbe28, 4)
41224/1:        lx_emulate(54) done (ret -22 / 0xffffffffffffffea ; errno 22)

truss -t setsockopt nodejs socket.js 
/1:     setsockopt(10, tcp, 0x22, 0x7FFFFFEFBE38, 4, SOV_DEFAULT) Err#22 EINVAL

set to 10 seconds+

41234/1:        setsockopt(11, 6, 4, 0x7fffffefbe28, 4)
41234/1:        lx_emulate(54) done (ret 0 / 0x0 ; errno 0)

which is correct as tcp_keepidle is just a wrapper around TCP_KEEPALIVE_THRESHOLD
and for this according to the manpage: The minimum value is ten seconds. The maximum is ten
days, while the default is two hours.

So you could argue it's a programmers error. Problem is linux does allow tcp_keepidle from 1 seconds+

Linux strace:
setsockopt(10, SOL_TCP, TCP_KEEPIDLE, [1], 4) = 0

tuxillo  reported this at #smartos irc channel. He has a programm that wants to set TCP_KEEPIDLE onto something less then 10 seconds.

Not sure how this should be addressed. 
I don't get why there is this 10 seconds minimum though.

**Comment by pfmooney** [comment]
Open as [OS-4686](https://smartos.org/bugview/OS-4686).
Thanks

**Comment by pfmooney** [comment]
Fixed in b4d3abce9796b4edf2c2b9c602ce5b7e7b877abf
