### ISSUE TITLE
[lx] some problem with epoll emulation

### ISSUE THREAD

**Issue by 4ad** [joyent/illumos-joyent#76]
Apologies for the very vague details on this bug, I haven't looked into it much, but it's trivial to reproduce, so it's worth filling a bug.

Create an lx zone, install rtorrent, try to download any torrent. rtorrent will start spinning on a number of CPUs doing no work.

**Comment by pfmooney** [comment]
Could you provide detail about the version of platform image (uname -v) and zone image you used for this test?

**Comment by 4ad** [comment]
The lx image is a781a350-07f4-11e5-9372-5f2886027fbc.

Platform image is smartos-20150917T232817Z-USB.img.

**Comment by pfmooney** [comment]
This looks like it could potentially be a signal-related bug.  I've opened [OS-4784](https://smartos.org/bugview/OS-4784).

Thanks

**Comment by pfmooney** [comment]
Fixed in a5f221fc261167afe807fe8a09777fc03221b93e.
